{$DEFINE FASTGZ}
//faster GZ decompression, requires 
//  Windows only : if you get an error "Can't find object file" you can copy the 'static' folder from
//    https://github.com/synopse/mORMot
//{$DEFINE PARALLEL}  //for parallel Unix also edit CThreads in LPR file - no benefit if used with DYNRGBA
//{$DEFINE DYNRGBA}  //{$IFDEF DYNRGBA}
{$DEFINE MOSAIC}
//{$DEFINE NEWPY} //It is suggested to use 2020.07.31 or earlier. This switch is for new versions https://github.com/Alexey-T/Python-for-Lazarus/issues/25

