.TH "MRICROGL" "1" "December 2021" "Yaroslav Halchenko" "User Commands"
.SH NAME
mricrogl \- magnetic resonance image conversion, viewing and analysis
.SH "DESCRIPTION"
MRIcroGL is a GUI-based visualization and analysis tool for medical imaging.
MRIcroGL can be used to create 2D or 3D renderings of statistical overlay maps
on brain anatomy images. Moreover, it aids drawing anatomical regions or
lesions.
.SH "AUTHOR"
\fBmricrogl\fR was written by Chris Rorden.
.PP
This manual page was written by Yaroslav Halchenko <debian@onerussian.com>,
for the Debian project (but may be used by others).
.SH "SEE ALSO"
.BR dcm2niix "(1)"
.TP
\fBMRIcroGL Homepage:\fR https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage
